[tool.poetry]
name = "repl_python3_Vehicle-Mod-Editor"
version = "0.1.0"
description = ""
authors = ["artprozew <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pytz = "^2021.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
